# Netlify Configuration for Next.js App Router
[build]
  command = "bun install && bun run build"
  publish = ".next"

  [build.environment]
    NODE_VERSION = "20"
    NEXT_TELEMETRY_DISABLED = "1"

# Essential redirects for Next.js App Router
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache API responses
[[headers]]
  for = "/api/site-configuration"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/api/subscription-plans"
  [headers.values]
    Cache-Control = "public, max-age=600"

# Don't cache user-specific APIs
[[headers]]
  for = "/api/user/*"
  [headers.values]
    Cache-Control = "private, no-cache"

[[headers]]
  for = "/api/admin/*"
  [headers.values]
    Cache-Control = "private, no-cache"

[[headers]]
  for = "/api/auth/*"
  [headers.values]
    Cache-Control = "private, no-cache"
